# Generated by Django 4.2.16 on 2026-06-14 13:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Rate to convert currency to group default (INR)', max_digits=10)),
                ('amount_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('paid_by_name', models.CharField(blank=True, max_length=100)),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('unequal', 'Unequal (fixed amounts)'), ('percentage', 'Percentage'), ('share', 'Share-based')], default='equal', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.group')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(blank=True, max_length=100)),
                ('owed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('split_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_splits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
